services:
  - type: web
    name: sequoia-retail-aum
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --timeout 180 --workers 1
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
